
spring:
  application:
    name: hystrix

server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

ribbon:
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
  OkToRetryOnAllOperations: true

#\u4E3A\u4E86\u6D4B\u8BD5 hystrix \u77ED\u8DEF\u529F\u80FD\uFF0C\u6211\u4EEC\u628A hystrix \u7B49\u5F85\u8D85\u65F6\u8BBE\u7F6E\u5F97\u975E\u5E38\u5C0F\uFF08500\u6BEB\u79D2\uFF09
#\u6B64\u8BBE\u7F6E\u4E00\u822C\u5E94\u5927\u4E8E ribbon \u7684\u91CD\u8BD5\u8D85\u65F6\u65F6\u957F\uFF0C\u4F8B\u5982 10 \u79D2
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
