
spring:
  application:
    name: zuul

server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul:
  retryable: true
  #zuul \u4F1A\u8FC7\u6EE4\u654F\u611F http \u534F\u8BAE\u5934 \u9ED8\u8BA4\u8FC7\u6EE4Cookie Set-Cookie Authorization \u8BBE\u7F6E\u4E0D\u8FC7\u6EE4\u8FD9\u4E9B
  sensitive-headers:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**

#\u5F00\u542Fribbon\u91CD\u8BD5
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1

#\u7194\u65AD\u964D\u7EA7
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500

#\u66B4\u9732\u76D1\u63A7\u7AEF\u70B9
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream