
spring:
  application:
    name: eureka-server

server:
  port: 2001

eureka:
  server:
    #eureka自我保护状态,当开启的时候将会尝试保护其服务注册表中的信息，
    #不再删除服务注册表中的数据。也就是不会注销任何微服务
    enable-self-preservation: false
  instance:
    hostname: eureka1
  client:
    service-url:
      #向eureka2中心注册
      defaultZone: http://eureka2:2002/eureka